### ISSUE TITLE
quantization

### ISSUE THREAD

**Issue by wm901115nwpu** [eladhoffer/convNet.pytorch#9]
If I use torch=0.2.0, I met the error:
Traceback (most recent call last):
  File "example/mpii.py", line 352, in <module>
    main(parser.parse_args())
  File "example/mpii.py", line 107, in main
    train_loss, train_acc = train(train_loader, model, criterion, optimizer, args.debug, args.flip)
  File "example/mpii.py", line 153, in train
    output = model(input_var)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 71, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/wangmeng/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangmeng/pytorch-pose-quantized/pose/models/hourglass_quantized.py", line 172, in forward
    x = self.conv1(x)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangmeng/pytorch-pose-quantized/pose/models/modules/quantize.py", line 188, in forward
    qinput = self.quantize_input(input)
  File "/home/wangmeng/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangmeng/pytorch-pose-quantized/pose/models/modules/quantize.py", line 165, in forward
    min_value * (1 - self.momentum))
TypeError: add_ received an invalid combination of arguments - got (Variable), but expected one of:
 * (float value)
      didn't match because some of the arguments have invalid types: (Variable)
 * (torch.cuda.FloatTensor other)
      didn't match because some of the arguments have invalid types: (Variable)
 * (torch.cuda.sparse.FloatTensor other)
      didn't match because some of the arguments have invalid types: (Variable)
 * (float value, torch.cuda.FloatTensor other)
 * (float value, torch.cuda.sparse.FloatTensor other)

Whether I need modified the models/modules/quantilized.py or not?

**Comment by blueardour** [comment]
Hi, a update version to pytorch 1.0 could fix your problem.
